### ISSUE TITLE
Add support for radicals

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [schang412/typst-whalogen#10]
In mhchem, radicals can be specified in the formula. However, it does not seem possible (or is not documented) for typst-whalogen.

Here is a bit of a hacky workaround in the meantime:

```
#import "@preview/whalogen:0.2.0": ce

$ ce("CH4^∙") $
```

Note that is a specific unicode character and not a . symbol. That makes it a bit annoying because you have to pull up the unicode character every time.

**Comment by wweatherall** [comment]
this may not help you, but on a mac you can access the '•' char by typing alt 8
